### ISSUE TITLE
编译伊始就提示LTO_clang 不支持

### ISSUE THREAD

**Issue by YakumoPANTS** [grislux55/Android_Kernel_Magic#2]
源码是NT内核最新（6月30？）
脚本如下
#!/bin/bash

export KERNELDIR=`readlink -f .`
export ARCH=arm64
export SUBARCH=arm64
export CLANG_PATH=/home/yakumo/kernel/Yukair-8P/toolchain/proton-clang-20200620/bin
export GCC_PATH=/home/yakumo/kernel/Yukair-8P/toolchain/arm64-gcc-master/bin
export GCC32_PATH=/home/yakumo/kernel/Yukair-8P/toolchain/arm32-gcc-master/bin
export PATH="$CLANG_PATH:$GCC_PATH:$GCC32_PATH:$PATH"
export CROSS_COMPILE=aarch64-elf-
export CROSS_COMPILE_ARM32=arm-eabi-

make vendor/neutrino_defconfig

echo "kerneldir = $KERNELDIR"

if [[ "${1}" == "skip" ]] ; then
	echo "Skipping Compilation"
else
	echo "Compiling kernel"
	cp defconfig .config
	make -j6 || exit 1
fi

出现错误如下
CHK     include/config/kernel.release
Cannot use CONFIG_LTO_CLANG: requires clang 5.0 or later
make: *** [Makefile:1254：prepare-compiler-check] 错误 1

但我第一次编译时使用全局的环境变量，AOSP的clang跑成功了
之后不管我换什么编译器都不行了，都这样

**Comment by grislux55** [comment]
请向make命令传递CC=clang参数以指示使用clang进行编译
